### ISSUE TITLE
Extract showcase applications into YAML file

### ISSUE THREAD

**Issue by locks** [emberjs/website#2749]
I'm currently working on adding a [showcase](https://github.com/emberjs/website/pull/2722) section to the Learn page, but I'm hard-coding everything.
We should extract the data into a YAML file, like we do for some other parts of the website, and render that data. This should avoid HTML errors and make the list easy to manage.

**Comment by locks** [comment]
I done gone and extracted it. I've ended up [with this](https://github.com/emberjs/website/commit/0dfa63dcefa7b85298d1fcf2f7ceddcee3e7be6b#diff-b402e4a8fc3af7005fd1b57222643947R26) based on your initial suggestion:

```yaml
- name:
  image:
    src:
    alt:
  repository:
  demo:
  description:
  features:
    -
```

I have added a commented-out placeholder to the bottom of the file, along with a commented out, specifying any rules necessary.
